// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include <functional>

namespace nativium
{
namespace enumerator
{

enum class CustomerStatusEnum : int
{
    ACTIVE,
    INACTIVE,
};

}
} // namespace nativium

namespace std
{

template <>
struct hash<::nativium::enumerator::CustomerStatusEnum>
{
    size_t operator()(::nativium::enumerator::CustomerStatusEnum type) const
    {
        return std::hash<int>()(static_cast<int>(type));
    }
};

} // namespace std
