// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/net/http/NTVHttpHeader.h"
#import "nativium/net/http/NTVHttpMethod.h"
#import "nativium/net/http/NTVHttpRequestParam.h"
#import <Foundation/Foundation.h>

@interface NTVHttpRequest : NSObject
- (nonnull instancetype)initWithUrl:(nonnull NSString *)url
                             method:(NTVHttpMethod)method
                             params:(nonnull NSArray<NTVHttpRequestParam *> *)params
                            headers:(nonnull NSArray<NTVHttpHeader *> *)headers
                               body:(nonnull NSString *)body;
+ (nonnull instancetype)httpRequestWithUrl:(nonnull NSString *)url
                                    method:(NTVHttpMethod)method
                                    params:(nonnull NSArray<NTVHttpRequestParam *> *)params
                                   headers:(nonnull NSArray<NTVHttpHeader *> *)headers
                                      body:(nonnull NSString *)body;

@property(nonatomic, readonly, nonnull) NSString *url;

@property(nonatomic, readonly) NTVHttpMethod method;

@property(nonatomic, readonly, nonnull) NSArray<NTVHttpRequestParam *> *params;

@property(nonatomic, readonly, nonnull) NSArray<NTVHttpHeader *> *headers;

@property(nonatomic, readonly, nonnull) NSString *body;

@end
