// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/net/http/NTVHttpHeader.h"
#import <Foundation/Foundation.h>

@interface NTVHttpResponse : NSObject
- (nonnull instancetype)initWithCode:(int32_t)code
                                body:(nonnull NSString *)body
                                 url:(nonnull NSString *)url
                             headers:(nonnull NSArray<NTVHttpHeader *> *)headers;
+ (nonnull instancetype)httpResponseWithCode:(int32_t)code
                                        body:(nonnull NSString *)body
                                         url:(nonnull NSString *)url
                                     headers:(nonnull NSArray<NTVHttpHeader *> *)headers;

@property(nonatomic, readonly) int32_t code;

@property(nonatomic, readonly, nonnull) NSString *body;

@property(nonatomic, readonly, nonnull) NSString *url;

@property(nonatomic, readonly, nonnull) NSArray<NTVHttpHeader *> *headers;

@end
