// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/net/http/NTVHttpRequestParam.h"

@implementation NTVHttpRequestParam

- (nonnull instancetype)initWithName:(nonnull NSString *)name
                               value:(nonnull NSString *)value
{
    if (self = [super init])
    {
        _name = [name copy];
        _value = [value copy];
    }
    return self;
}

+ (nonnull instancetype)httpRequestParamWithName:(nonnull NSString *)name
                                           value:(nonnull NSString *)value
{
    return [(NTVHttpRequestParam *)[self alloc] initWithName:name
                                                       value:value];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p name:%@ value:%@>", self.class, (void *)self, self.name, self.value];
}

@end
