// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/net/http/HttpResponse.hpp"
#import "nativium/net/http/NTVHttpResponse.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVHttpResponse;

namespace djinni_generated
{

struct HttpResponse
{
    using CppType = ::nativium::net::http::HttpResponse;
    using ObjcType = ::NTVHttpResponse *;

    using Boxed = HttpResponse;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType &cpp);
};

} // namespace djinni_generated
