# variables
IOS_PLATFORM = '9.0'
WATCHOS_PLATFORM = '6.2'
NATIVIUM_SDK_LOCAL = false
NATIVIUM_SDK_VERSION = '1.0.0'

# settings
use_frameworks!

# dependencies
def shared_pods
  
  if NATIVIUM_SDK_LOCAL
    pod 'nativium', :http => 'http://127.0.0.1:8000/dist.tar.gz'
    else
    pod 'nativium', :http => 'https://nativium.s3.amazonaws.com/dist/ios/' + NATIVIUM_SDK_VERSION + '/dist.tar.gz'
  end

end

target 'Sample' do
  platform :ios, IOS_PLATFORM
  shared_pods
end

target 'Sample-AppleWatch Extension' do
  platform :watchos, WATCHOS_PLATFORM
  shared_pods
end

post_install do |installer|
  
  installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
              config.build_settings['EXCLUDED_ARCHS[sdk=watchsimulator*]'] = 'arm64 i386'
        end
  end
  
end
