// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/net/http/NTVHttpServerConfig.h"

@implementation NTVHttpServerConfig

- (nonnull instancetype)initWithPort:(int32_t)port
                          staticPath:(nonnull NSString *)staticPath
{
    if (self = [super init])
    {
        _port = port;
        _staticPath = [staticPath copy];
    }
    return self;
}

+ (nonnull instancetype)httpServerConfigWithPort:(int32_t)port
                                      staticPath:(nonnull NSString *)staticPath
{
    return [(NTVHttpServerConfig *)[self alloc] initWithPort:port
                                                  staticPath:staticPath];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p port:%@ staticPath:%@>", self.class, (void *)self, @(self.port), self.staticPath];
}

@end
