// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/systemservice/NTVSystemServiceCustomerSystemServiceLoginData.h"

@implementation NTVSystemServiceCustomerSystemServiceLoginData

- (nonnull instancetype)initWithResponse:(nonnull NTVDomainResponse *)response
                                customer:(nonnull NTVDomainCustomer *)customer
{
    if (self = [super init])
    {
        _response = response;
        _customer = customer;
    }
    return self;
}

+ (nonnull instancetype)customerSystemServiceLoginDataWithResponse:(nonnull NTVDomainResponse *)response
                                                          customer:(nonnull NTVDomainCustomer *)customer
{
    return [(NTVSystemServiceCustomerSystemServiceLoginData *)[self alloc] initWithResponse:response
                                                                                   customer:customer];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p response:%@ customer:%@>", self.class, (void *)self, self.response, self.customer];
}

@end
